### ISSUE TITLE
[0.4.0] Exception when reading item damage stats

### ISSUE THREAD

**Issue by squeek502** [Zutatensuppe/DiabloInterface#32]
Opening the debug window or querying items through the pipe server throws:

```
Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at Zutatensuppe.D2Reader.Readers.RangeStatDamage._toString(StringLookupTable stringLookupTable, Int32[] args, UInt16stringId) in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\RangeStatData.cs:line 50
   at Zutatensuppe.D2Reader.Readers.RangeStatDamage.ToString(StringLookupTable stringLookupTable) in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\RangeStatData.cs:line 37
   at Zutatensuppe.D2Reader.Readers.RangeStatData.TryHandleStat(D2Stat stat, String& description) in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\RangeStatData.cs:line 232
   at Zutatensuppe.D2Reader.Readers.ItemReader.<>c__DisplayClass49_0.<GetMagicalStrings>g__getDescription0(D2Stat stat)in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\ItemReader.cs:line 865
   at Zutatensuppe.D2Reader.Readers.ItemReader.<>c__DisplayClass49_0.<GetMagicalStrings>b__4(<>f__AnonymousType1`2 <>h__TransparentIdentifier0) in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\ItemReader.cs:line 877
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.<ReverseIterator>d__74`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Zutatensuppe.D2Reader.Readers.ItemReader.GetMagicalStrings(D2Unit item) in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\ItemReader.cs:line 874
   at Zutatensuppe.D2Reader.D2DataReader.ReadEquippedItemStrings() in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\D2DataReader.cs:line 444
   at Zutatensuppe.D2Reader.D2DataReader.ProcessEquippedItemStrings() in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\D2DataReader.cs:line 425
   at Zutatensuppe.D2Reader.D2DataReader.ProcessGameData() in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\D2DataReader.cs:line 349
   at Zutatensuppe.D2Reader.D2DataReader.RunReadOperation() in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\D2DataReader.cs:line 266Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at Zutatensuppe.D2Reader.Readers.RangeStatDamage._toString(StringLookupTable stringLookupTable, Int32[] args, UInt16stringId) in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\RangeStatData.cs:line 50
   at Zutatensuppe.D2Reader.Readers.RangeStatDamage.ToString(StringLookupTable stringLookupTable) in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\RangeStatData.cs:line 37
   at Zutatensuppe.D2Reader.Readers.RangeStatData.TryHandleStat(D2Stat stat, String& description) in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\RangeStatData.cs:line 232
   at Zutatensuppe.D2Reader.Readers.ItemReader.<>c__DisplayClass49_0.<GetMagicalStrings>g__getDescription0(D2Stat stat)in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\ItemReader.cs:line 865
   at Zutatensuppe.D2Reader.Readers.ItemReader.<>c__DisplayClass49_0.<GetMagicalStrings>b__4(<>f__AnonymousType1`2 <>h__TransparentIdentifier0) in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\ItemReader.cs:line 877
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.<ReverseIterator>d__74`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Zutatensuppe.D2Reader.Readers.ItemReader.GetMagicalStrings(D2Unit item) in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\Readers\ItemReader.cs:line 874
   at Zutatensuppe.D2Reader.D2DataReader.ReadEquippedItemStrings() in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\D2DataReader.cs:line 444
   at Zutatensuppe.D2Reader.D2DataReader.ProcessEquippedItemStrings() in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\D2DataReader.cs:line 425
   at Zutatensuppe.D2Reader.D2DataReader.ProcessGameData() in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\D2DataReader.cs:line 349
   at Zutatensuppe.D2Reader.D2DataReader.RunReadOperation() in C:\Users\Ryan\Programming\Diablo\DiabloInterface\src\D2Reader\D2DataReader.cs:line 266
```

EDIT: Happens on both 1.13 and 1.14. Only appears to trigger when certain items are equipped. Will try to narrow it down.

EDIT#2: Seems to be triggered by War Travelers being equipped, oddly enough.

EDIT#3: It's any item that has a `Adds X-Y damage` stat (war travs add `15-20` damage). Elemental damage seems to be okay.

EDIT#4: Actually seems to affect all damage stats, but it only throws exceptions for phys damage. Elemental damage just doesn't show up in the stat readout at all (e.g. SoJ stats don't include `1-12 lightning damage`)

**Comment by Zutatensuppe** [comment]
fixed by squeek502 in #33 👍
